In [13]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
data = pd.read_csv("D:/PROJECTS/system-log-anomaly-detection/data/raw/logging_monitoring_anomalies_dirty.csv")

C:\Users\hp\AppData\Local\Temp\ipykernel_20208\3342052113.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("D:/PROJECTS/system-log-anomaly-detection/data/raw/logging_monitoring_anomalies_dirty.csv")

In [15]:
data.head()

,Timestamp,Anomaly_ID,Anomaly_Type,Severity,Status,Source,Alert_Method,Response_Time_ms,Resolution_Time_min,Affected_Services,...,Anomaly_Duration_sec,TimeZone,User_ID,Location,Patch_Level,Service_Type,Transaction_ID,Alert_Count,Retry_Count,Escalation_Level
0,2025-01-01 00:00:00,1,Storage,Low,Open,Database,SMS,2612.0,25.0,18.0,...,43,PST,23536,APAC,4,Cache,195883,40,7,3
1,2025-01-01 00:01:00,2,Database,Medium,Closed,Server,Email,5375.0,2046.0,3.0,...,7146,IST,10030,US,0,API,952949,18,7,0
2,2025-01-01 00:02:00,3,Network,High,Acknowledged,Cloud,Webhook,7789.0,3016.0,3.0,...,1588,PST,11907,EU,12,Web,534080,32,6,1
3,2025-01-01 00:03:00,4,Application,Medium,Open,Database,SMS,361.0,757.0,9.0,...,1301,PST,32768,APAC,7,Web,452955,36,0,3
4,2025-01-01 00:04:00,5,Database,Low,Acknowledged,Firewall,SMS,935.0,1077.0,4.0,...,4336,PST,26202,APAC,14,Web,694799,39,8,2

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100200 entries, 0 to 100199
Data columns (total 31 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Timestamp             100200 non-null  object
 1   Anomaly_ID            100200 non-null  int64
 2   Anomaly_Type          100200 non-null  object
 3   Severity              100200 non-null  object
 4   Status                100200 non-null  object
 5   Source                99697 non-null   object
 6   Alert_Method          99699 non-null   object
 7   Response_Time_ms      99702 non-null   object
 8   Resolution_Time_min   99699 non-null   object
 9   Affected_Services     99702 non-null   float64
 10  User_Role             100200 non-null  object
 11  Host_IP               100200 non-null  object
 12  Process_ID            100200 non-null  int64
 13  Error_Code            100200 non-null  int64
 14  CPU_Usage_Percent     100200 non-null  float64
 15  Memory_Usage_MB       100200 non-null  int64
 16  Disk_Usage_Percent    100200 non-null  float64
 17  Network_In_KB         100200 non-null  int64
 18  Network_Out_KB        100200 non-null  int64
 19  Login_Attempts        100200 non-null  int64
 20  Failed_Transactions   100200 non-null  int64
 21  Anomaly_Duration_sec  100200 non-null  int64
 22  TimeZone              100200 non-null  object
 23  User_ID               100200 non-null  int64
 24  Location              100200 non-null  object
 25  Patch_Level           100200 non-null  int64
 26  Service_Type          100200 non-null  object
 27  Transaction_ID        100200 non-null  int64
 28  Alert_Count           100200 non-null  int64
 29  Retry_Count           100200 non-null  int64
 30  Escalation_Level      100200 non-null  int64
dtypes: float64(3), int64(15), object(13)
memory usage: 23.7+ MB

In [6]:
data.describe()

,Anomaly_ID,Affected_Services,Process_ID,Error_Code,CPU_Usage_Percent,Memory_Usage_MB,Disk_Usage_Percent,Network_In_KB,Network_Out_KB,Login_Attempts,Failed_Transactions,Anomaly_Duration_sec,User_ID,Patch_Level,Transaction_ID,Alert_Count,Retry_Count,Escalation_Level
count,1.002000e+05,99702.000000,1.002000e+05,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000,100200.000000
mean,5.988725e+04,11.890022,6.040661e+04,5056.084451,50.001879,32059.267255,49.964446,500595.108832,499175.307605,24.506876,9.517016,3603.917595,25456.614192,9.515649,550592.187136,25.014511,4.505439,2.005309
std,2.228040e+05,42.414639,2.227463e+05,2856.156887,28.846073,18450.515958,28.803756,289284.715559,288347.049082,14.403543,5.767666,2076.616787,14162.981639,5.767800,259971.132447,14.109515,2.876724,1.414062
min,1.000000e+00,1.000000,1.001000e+03,100.000000,0.000000,100.000000,0.000000,2.000000,2.000000,0.000000,0.000000,1.000000,1000.000000,0.000000,100000.000000,1.000000,0.000000,0.000000
25%,2.506075e+04,5.000000,2.570875e+04,2578.750000,24.990000,16069.250000,25.160000,250115.250000,250226.500000,12.000000,5.000000,1808.000000,13206.000000,5.000000,325050.250000,13.000000,2.000000,1.000000
50%,5.011050e+04,10.000000,5.064550e+04,5053.000000,50.040000,32118.500000,49.850000,501318.500000,498289.000000,24.000000,10.000000,3592.000000,25420.000000,9.000000,550855.000000,25.000000,4.000000,2.000000
75%,7.516025e+04,15.000000,7.549700e+04,7528.000000,74.940000,48051.000000,74.760000,751349.750000,747460.250000,37.000000,15.000000,5408.250000,37797.250000,15.000000,775597.000000,37.000000,7.000000,3.000000
max,5.000000e+06,950.000000,4.999900e+06,9998.000000,100.000000,63999.000000,100.000000,999997.000000,999991.000000,49.000000,19.000000,7199.000000,49999.000000,19.000000,999986.000000,49.000000,9.000000,4.000000

### Fix Incorrect Data Types

In [7]:
data['Response_Time_ms'] = pd.to_numeric(data['Response_Time_ms'], errors='coerce')

data['Resolution_Time_min'] = pd.to_numeric(data['Resolution_Time_min'], errors='coerce')

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100200 entries, 0 to 100199
Data columns (total 31 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Timestamp             100200 non-null  object
 1   Anomaly_ID            100200 non-null  int64
 2   Anomaly_Type          100200 non-null  object
 3   Severity              100200 non-null  object
 4   Status                100200 non-null  object
 5   Source                99697 non-null   object
 6   Alert_Method          99699 non-null   object
 7   Response_Time_ms      99502 non-null   float64
 8   Resolution_Time_min   99499 non-null   float64
 9   Affected_Services     99702 non-null   float64
 10  User_Role             100200 non-null  object
 11  Host_IP               100200 non-null  object
 12  Process_ID            100200 non-null  int64
 13  Error_Code            100200 non-null  int64
 14  CPU_Usage_Percent     100200 non-null  float64
 15  Memory_Usage_MB       100200 non-null  int64
 16  Disk_Usage_Percent    100200 non-null  float64
 17  Network_In_KB         100200 non-null  int64
 18  Network_Out_KB        100200 non-null  int64
 19  Login_Attempts        100200 non-null  int64
 20  Failed_Transactions   100200 non-null  int64
 21  Anomaly_Duration_sec  100200 non-null  int64
 22  TimeZone              100200 non-null  object
 23  User_ID               100200 non-null  int64
 24  Location              100200 non-null  object
 25  Patch_Level           100200 non-null  int64
 26  Service_Type          100200 non-null  object
 27  Transaction_ID        100200 non-null  int64
 28  Alert_Count           100200 non-null  int64
 29  Retry_Count           100200 non-null  int64
 30  Escalation_Level      100200 non-null  int64
dtypes: float64(5), int64(15), object(11)
memory usage: 23.7+ MB

### Handle Missing Values

In [10]:
data['Source'] = data['Source'].fillna("Unknown")

data['Alert_Method'] = data['Alert_Method'].fillna("Unknown")

data['Response_Time_ms'] = data['Response_Time_ms'].fillna(data['Response_Time_ms'].median())

data['Resolution_Time_min'] = data['Resolution_Time_min'].fillna(data['Resolution_Time_min'].median())

data['Affected_Services'] = data['Affected_Services'].fillna(data['Affected_Services'].median())

In [11]:
data.isnull().sum()

Timestamp               0
Anomaly_ID              0
Anomaly_Type            0
Severity                0
Status                  0
Source                  0
Alert_Method            0
Response_Time_ms        0
Resolution_Time_min     0
Affected_Services       0
User_Role               0
Host_IP                 0
Process_ID              0
Error_Code              0
CPU_Usage_Percent       0
Memory_Usage_MB         0
Disk_Usage_Percent      0
Network_In_KB           0
Network_Out_KB          0
Login_Attempts          0
Failed_Transactions     0
Anomaly_Duration_sec    0
TimeZone                0
User_ID                 0
Location                0
Patch_Level             0
Service_Type            0
Transaction_ID          0
Alert_Count             0
Retry_Count             0
Escalation_Level        0
dtype: int64

### Feature Engineering

In [17]:
data['Timestamp'] = pd.to_datetime(data['Timestamp'], errors='coerce')

In [18]:
data = data.dropna(subset=['Timestamp'])

In [19]:
print(data['Timestamp'].dtype)

datetime64[ns]

In [20]:
data['Timestamp'].isnull().sum()

0

In [21]:
data['hour'] = data['Timestamp'].dt.hour
data['day'] = data['Timestamp'].dt.day
data['month'] = data['Timestamp'].dt.month

### Encode Severity

In [23]:
severity_map = {
    "Low":1,
    "Medium":2,
    "High":3
}

data['Severity_Level'] = data['Severity'].map(severity_map)

### Drop Unnecessary Columns


Host_IP
Transaction_ID
User_ID

In [24]:
data = data.drop(columns=['Host_IP'])

### Save Processed Dataset

In [25]:
data.to_csv("D:/PROJECTS/system-log-anomaly-detection/data/processed/logs_cleaned.csv", index=False)